### ISSUE TITLE
Twitch Chat Emotes don't work

### ISSUE THREAD

**Issue by nestlols** [night/BetterTTV#160]
Twitch Chat Emotes don't work

**Comment by cletusc** [comment]
Looking into this now.

**Comment by cletusc** [comment]
All progress will be over at cletusc/Userscript--Twitch-Chat-Emotes#72 for those looking for updates. This should stay open until the fix is in place in the BTTV copy.

**Comment by saybyebyeb** [comment]
Hello my emotes are not working also

**Comment by Mrbysco** [comment]
Mine aren't working either... I cant auto insert them anymore

**Comment by Goofyd00d** [comment]
Ya, the button to see all available emotes and click to insert will not appear, have tried clearing cache and cookies, reinstall and all that, nothing.  Unfortunate, used some xmas bonus to subscribe to a lot of channels.

**Comment by cletusc** [comment]
For those watching this issue, I pushed an update last night to [the standalone](http://cletusc.github.io/Userscript--Twitch-Chat-Emotes/#install). Support for BTTV custom emotes still needs to be added, but it's a start.

**Comment by Jahdoh** [comment]
Thank you cletusc very much.

**Comment by night** [comment]
Fixed. Clear your cookies and cache if you still have problems.

**Comment by saybyebyeb** [comment]
Thank you they are back for me now

**Comment by ZeTaurin** [comment]
Mine are still not working, i disabled the emotes and enabled them again and i even reinstalled the extension.
