### ISSUE TITLE
Chat broken

### ISSUE THREAD

**Issue by TheStario** [night/BetterTTV#1898]
So, I am unsure if it is a Safari specific issue but when I load into a live channel I can see the chat and everything as normal, besides the fact that nothing in chat loads and it's blank (minus cheers at the top). I cannot type into the chatbox below either, it just says "Send a Message" and when I click it nothing happens. I can put emotes in through clicking the icon though.

When I disable BTTV I can use chat as normal again, so I am assuming it is a BTTV issue. I hope this can be fixed soon.

**Comment by SW1FT** [comment]
I have the same problem on Firefox 52, it's random but it happens more than it doesn't. The only workaround is opening the chat in popup mode.

**Comment by Thalenia** [comment]
Also having this issue in Safari, I assume after the latest update (which was auto-downloaded).  Chat doesn't load, though I can see special messages like subscribes and cheers and other pop-up messages.  No issues when BTTV is disabled.  Sometimes I see things flashing in the chat before disappearing, if that means anything.  No BTTV graphic next to the Twitch logo.

Pop-out chat works fine.

No BTTV settings are available in either imbedded or pop-out chat, so I if it is loading, it is not loading fully.

I get a number of extension-related errors in the console (see below) that I can't decipher.  This is with no other extensions enabled.

If I log out of Twitch and go to a channel, chat works fine, and the BTTV settings are available again in the chat settings.  I can open up highlight and blacklist options, but the link for settings doesn't do anything (not sure what it used to do if anything).  Dark mode does change the other settings links for BTTV to have symbols covering the text, which doesn't happen with Twitch's dark mode.

Note that the errors below still show up in console when not logged in.

Also, occasionally the video will load but not play, sometimes requiring multiple reloads to work.  I don't know if that is related or not, it seems a LOT more frequent now (where it was pretty rare earlier).


[Error] XMLHttpRequest cannot load chrome-extension://hfaagokkkhdbgiakmmlclaapfelnkoah/cast_sender.js. Cross origin requests are only supported for HTTP.
	isExtensionInstalled_ (global-d6fad0cf05fa7aa7c5cb66f0bff5e07d.js:29:17392)
	findInstalledExtensionHelper_ (global-d6fad0cf05fa7aa7c5cb66f0bff5e07d.js:29:16891)
	(anonymous function) (global-d6fad0cf05fa7aa7c5cb66f0bff5e07d.js:29:17035)
	onerror (global-d6fad0cf05fa7aa7c5cb66f0bff5e07d.js:29:17321)

[Error] XMLHttpRequest cannot load chrome-extension://fmfcbgogabcbclcofgocippekhfcmgfj/cast_sender.js. Cross origin requests are only supported for HTTP.
	isExtensionInstalled_ (global-d6fad0cf05fa7aa7c5cb66f0bff5e07d.js:29:17392)
	findInstalledExtensionHelper_ (global-d6fad0cf05fa7aa7c5cb66f0bff5e07d.js:29:16891)
	(anonymous function) (global-d6fad0cf05fa7aa7c5cb66f0bff5e07d.js:29:17035)
	onerror (global-d6fad0cf05fa7aa7c5cb66f0bff5e07d.js:29:17321)
	send
	isExtensionInstalled_ (global-d6fad0cf05fa7aa7c5cb66f0bff5e07d.js:29:17392)
	findInstalledExtensionHelper_ (global-d6fad0cf05fa7aa7c5cb66f0bff5e07d.js:29:16891)
	(anonymous function) (global-d6fad0cf05fa7aa7c5cb66f0bff5e07d.js:29:17035)
	onerror (global-d6fad0cf05fa7aa7c5cb66f0bff5e07d.js:29:17321)

[Error] XMLHttpRequest cannot load chrome-extension://enhhojjnijigcajfphajepfemndkmdlo/cast_sender.js. Cross origin requests are only supported for HTTP.
	isExtensionInstalled_ (global-d6fad0cf05fa7aa7c5cb66f0bff5e07d.js:29:17392)
	findInstalledExtensionHelper_ (global-d6fad0cf05fa7aa7c5cb66f0bff5e07d.js:29:16891)
	(anonymous function) (global-d6fad0cf05fa7aa7c5cb66f0bff5e07d.js:29:17035)
	onerror (global-d6fad0cf05fa7aa7c5cb66f0bff5e07d.js:29:17321)
	send
	isExtensionInstalled_ (global-d6fad0cf05fa7aa7c5cb66f0bff5e07d.js:29:17392)
	findInstalledExtensionHelper_ (global-d6fad0cf05fa7aa7c5cb66f0bff5e07d.js:29:16891)
	(anonymous function) (global-d6fad0cf05fa7aa7c5cb66f0bff5e07d.js:29:17035)
	onerror (global-d6fad0cf05fa7aa7c5cb66f0bff5e07d.js:29:17321)
	send
	isExtensionInstalled_ (global-d6fad0cf05fa7aa7c5cb66f0bff5e07d.js:29:17392)
	findInstalledExtensionHelper_ (global-d6fad0cf05fa7aa7c5cb66f0bff5e07d.js:29:16891)
	(anonymous function) (global-d6fad0cf05fa7aa7c5cb66f0bff5e07d.js:29:17035)
	onerror (global-d6fad0cf05fa7aa7c5cb66f0bff5e07d.js:29:17321)

**Comment by night** [comment]
Do you guys use FrankerFaceZ in combination with BetterTTV? Does disabling fix it?

**Comment by SW1FT** [comment]
@night I don't use that addon..

**Comment by Thalenia** [comment]
Never heard of FrankerFaceZ @night .  I disabled all other plugins when testing the issues anyway, so there should be no conflicts from them.

**Comment by night** [comment]
Do you all use automatic theater mode? Is the issue fixed now? I cannot reproduce any issues, so unless there's a reproducible bug here we can't resolve the issue.

**Comment by SW1FT** [comment]
I don't use automatic theater mode, however I'm not having the issue at the moment... If I get it, I'll update this comment.

**Comment by Thalenia** [comment]
@night Just logged in a minute ago (no theater mode), and everything seems to be right.  Chat works, BTTV is definitely working, menu shows up as it should etc.  Something definitely changed since last night.  I'll still play around and see what happens, but at this moment things seem to be working 100% as intended.

**Comment by Thalenia** [comment]
Just to close the loop...I'm still having this issue at near 100% of the time.  I've found that occasionally (<1%), BTTV will run if I reload the page, but other than that it completely breaks chat AND doesn't load.

The video playback bug seems to be a bug in the java player, but could be related somehow.

Oddly, in watching the error console, I only get errors specifically referencing BTTV when it loads correctly.  Maybe that's expected though.

**Comment by RandomGOTI** [comment]
Same issues only thing that i see in chat are those most of the times or the chat bugs out and doesn't load at all

> BetterTTV v6.8 Loaded.
> 7:10 Welcome to x's chat room!
> 7:10 x has been timed out.
> 7:10 x has been timed out.
> 7:11 x has been timed out.
> 7:11 x has been timed out.
> 7:11 x has been timed out.
> 7:11  x just subscribed with Twitch Prime!
> 7:11 x has been timed out.
> 7:12 x has been timed out.

Gogole Chrome 55.0.2883.87 m (64-bit)

**Comment by WasabiIceCream** [comment]
Just here to echo some of the same issues.
Pretty much every channel I enter, the chat like, loads normally before the plugin hooks into it.
Then, once the page fully loads, the messages that were there disappear. This is when it breaks.
Strange thing is, I can still type messages, people can see and respond to them, but I can't see anything.
What's even stranger is, my channel, the one I use all the time (under a different account even), always works fine, but almost any other channel is broken for me.

Just some examples, so you guys can maybe see for yourself.
For me, Monstercat's 24/7 music channel is always broken: https://www.twitch.tv/monstercat
And, this one always works: https://www.twitch.tv/gameoverse

**Comment by mparkms** [comment]
I am getting the same issue on Firefox 52.0a2. Chrome works fine. I can also confirm that I am getting the same behavior as WasabiIceCream. Occasionally, BetterTTV fails to load for the chat only (the BetterTTV loaded message does not appear and I can't access BetterTTV settings from the chat settings, but the rest of the extension seems to load nromally), and the chat works as normal. 

I've been having this problem for several weeks now, and it makes the extension unusable.

**Comment by shelterx** [comment]
I have this bug too in Firefox 54 nightly. I understand I might be running on an unsupported Firefox version but here are my findings:
On my main computer, an i7 with SSD, chat _mostly_ loads fine, even when e10s is enabled.

However on my laptop (an i5 with mechanial drive) with the exact same Firefox and profile files as the main computer, chat usually never loads when e10s is enabled.
If I disable e10s, chat loads sometimes if I am lucky.

If I pop out the chat window then chat always works on both computers.

Race condition?

**Comment by erasedff** [comment]
Broken for me as well, using Firefox 54.
Even if I use BTTV from Chrome via ChromeStoreFoxified, chat is still broken. However if I disable BTTV, then open the stream page and then enable BTTV, the extension loads fine without the page refresh and chat is working. But I have to do this every time I open a stream in order for chat to work.

**Comment by deathkneel** [comment]
I have the same problem on Firefox 52.0 (64-bit). I got it since 2 days ago when firefox did an update.

**Comment by fran-penedo** [comment]
Same issue in Chrome 55 with FrankerFaceZ, disabling it solves the issue. Maybe try reproducing it with FFZ? It sounds like the same issue, even if it's triggered by something else.

**Comment by night** [comment]
If you're still having issues, we released a beta version of BetterTTV v7, which is a complete rewrite. It should address these race issues plaguing the extension for so long.

To try it out, enable the beta from the BetterTTV settings. Note: Currently when you turn on the beta, there's no way back. If you want to go back, you need to clear your cookies (thus losing your settings). If you want to save your settings just in case, make a backup before turning on the beta.

**Comment by Cregavitch** [comment]
@night saw this thread on google because I've been having the same issue as everyone else in this thread for the past month, refreshing fixed the issue but I got sick of it and looked around only to find this thread. Updating the v7 fixed the issue for me! Thank you and keep up the good work!
